# @package _global_

data:
  task_name: KB_HellaSwag
  max_length: 256

optim:
  epochs: 10
  batch_size: 8
  grad_acc: 1
  base_lr: 1e-02
  dropout_prob: 0.1
  warmup_ratio: 0.1

logging:
  log_steps: 50

