# @package _global_

data:
  task_name: KoCommonGen
  max_length: 128

optim:
  epochs: 5
  train_batch_size: 64
  grad_acc: 1
  eval_batch_size: 64
  base_lr: 1e-04
  dropout_prob: 0.1
  warmup_ratio: 0.1

logging:
  log_steps: 100

