# @package _global_

data:
  task_name: KorQuAD
  max_length: 512
  threads: 10
  version_2_with_negative: false
  null_score_diff_threshold: 0.0
  doc_stride: 128
  max_query_len: 64
  max_answer_len: 30
  n_best_size: 20
  verbose_logging: true

optim:
  epochs: 5
  batch_size: 16
  grad_acc: 1
  base_lr: 5e-5
  adam_epsilon: 1e-8

logging:
  log_steps: 200
