# @package _global_

data:
  task_name: KoCommonGen
  max_length: 128

model:
  generation_config:
    min_length: 10
    max_length: 128
    max_new_tokens: 30
    no_repeat_ngram_size: 3
    do_sample: false
    num_beams: 5
  sub2:
    embedding_norm: true

optim:
  epochs: 15
  train_batch_size: 64
  grad_acc: 1
  eval_batch_size: 16
  base_lr: 1e-04
  dropout_prob: 0.1
  warmup_ratio: 0.1

logging:
  log_steps: 100

