# @package _global_

data:
  task_name: KoreanGEC_native
  max_length:

model:
  generation_config:
    min_length:
    max_length: 32
    max_new_tokens: 32
#    no_repeat_ngram_size: 3
    do_sample: false
    num_beams: 4
  sub2:
    tok_type: jamo_var
    max_length: 1024

optim:
  epochs: 10
  train_batch_size: 64
  grad_acc: 1
  eval_batch_size: 64
  base_lr: 1e-02
  dropout_prob: 0.1
  warmup_ratio: 0.1

logging:
  log_steps: 15

